version: "{build}-{branch}"

branches:
  except: 
    - gh-pages

environment:
  scoop: c:\tools\scoop

init:
  - ps: (Get-PSProvider FileSystem).Home = 'c:\tools\'
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop install invoke-build

build: off

test_script:
  - ps: invoke-build test

notifications:
  - provider: Slack
    auth_token:
      secure: lzkktSx/4RFbuzbztN3ZycdGJjr6ZqapatvExhwRjB4Va9QNutHw1lGPI0hWlPAq
    channel: activity